version: '3.8'

services:
  # Automatic Nginx Proxy with SSL
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      - "com.github.nginx-proxy.nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - gamestash-network
    restart: unless-stopped

  # Automatic SSL Certificate Management
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    env_file:
      - ./server/.env
    environment:
      DEFAULT_EMAIL: alton.liu.cs@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    networks:
      - gamestash-network
    restart: unless-stopped
    depends_on:
      - nginx-proxy

  # Redis for session storage
  redis:
    image: redis:7-alpine
    container_name: gamestash-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-DefaultRedisPass2025!}
    volumes:
      - redis_data:/data
    networks:
      - gamestash-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: gamestash-postgres
    env_file:
      - ./server/.env
    environment:
      POSTGRES_DB: gamestash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecureP@ssw0rd_2025_GameStash_Prod_Database!
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - gamestash-network
    restart: unless-stopped
    command: >
      postgres 
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  # Backend API Server
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: gamestash-backend
    env_file:
      - ./server/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: gamestash
      DB_USER: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-DefaultRedisPass2025!}
      NODE_ENV: production
      FRONTEND_URLS: http://localhost:4200,https://gamestash.live,https://www.gamestash.live,https://api.gamestash.live
      VIRTUAL_HOST: api.gamestash.live
      LETSENCRYPT_HOST: api.gamestash.live
    expose:
      - "3000"
    depends_on:
      - postgres
      - redis
    networks:
      - gamestash-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./game-stash
      dockerfile: Dockerfile
    container_name: gamestash-frontend
    environment:
      # Backend API URL for production deployment
      API_URL: https://api.gamestash.live
      VIRTUAL_HOST: gamestash.live,www.gamestash.live
      LETSENCRYPT_HOST: gamestash.live,www.gamestash.live
    expose:
      - "80"
    networks:
      - gamestash-network
    restart: unless-stopped

networks:
  gamestash-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
